### ISSUE TITLE
WIFI联网问题

### ISSUE THREAD

**Issue by anonier** [Raysamatoken/macOS-HaseeX5-ShinelonL9#1]
我搜了teloport，但是网上没有任何相关信息，我想问问应该怎么连上WiFi

**Comment by Raysamatoken** [comment]
不好意思，软件名打错了，直接从这里下载这个软件就好了
https://github.com/OpenIntelWireless/HeliPort/releases

**Comment by anonier** [comment]
成功了，谢谢你的项目
